// products.js
export const products = [
    {
        id: 1,
        name: "Queso Frito Frito",
        price: 500,
        image: "https://i.postimg.cc/4dq9XMN9/queso.jpg",
        productDetails: "",
        isVegan: false,
        isVegetarian: false,
        isGlutenFree: false,
        dietaryInfo: "",
        categories: ["Adicionales"],
        order: 999,
        comercioId: "J7plAoTSgUmTXxaQ4gnT",
        comercioName: "La Choza del Pueblo"
    },
    {
        id: 2,
        name: "Sandwich Carne o Pollo",
        price: 2200,
        image: "https://i.postimg.cc/y8DCZbVd/sandwich-carne.webp",
        productDetails: "Acompañado con Queso y Tocineta",
        isVegan: false,
        isVegetarian: false,
        isGlutenFree: false,
        dietaryInfo: "",
        categories: [],
        order: 999,
        comercioId: "J7plAoTSgUmTXxaQ4gnT",
        comercioName: "La Choza del Pueblo"
    },
    {
        id: 3,
        name: "Olla de Carne ",
        price: 3500,
        image: "https://i.postimg.cc/Tw5NQzK7/olla-carne.jpg",
        productDetails: "",
        isVegan: false,
        isVegetarian: false,
        isGlutenFree: false,
        dietaryInfo: "",
        categories: [],
        order: 999,
        comercioId: "J7plAoTSgUmTXxaQ4gnT",
        comercioName: "La Choza del Pueblo"
    },
    {
        id: 4,
        name: "Salchichón",
        price: 500,
        image: "https://i.postimg.cc/ZYvNwTVF/salchichon.jpg",
        productDetails: "",
        isVegan: false,
        isVegetarian: false,
        isGlutenFree: false,
        dietaryInfo: "",
        categories: ["Adicionales", "Desayunos"],
        order: 999,
        comercioId: "J7plAoTSgUmTXxaQ4gnT",
        comercioName: "La Choza del Pueblo"
    },
    {
        id: 5,
        name: "Gallo torta huevo",
        price: 1200,
        image: "https://i.postimg.cc/23p8tNj0/gallo-de-torta-de-huevo.jpg",
        productDetails: "",
        isVegan: false,
        isVegetarian: false,
        isGlutenFree: false,
        dietaryInfo: "",
        categories: ["Gallos", "Desayunos"],
        order: 999,
        comercioId: "J7plAoTSgUmTXxaQ4gnT",
        comercioName: "La Choza del Pueblo"
    },
    {
        id: 6,
        name: "Palitos de queso ",
        price: 2000,
        image: "https://i.postimg.cc/tTQbyNGg/palitos-de-queso.webp",
        productDetails: "",
        isVegan: false,
        isVegetarian: false,
        isGlutenFree: false,
        dietaryInfo: "",
        categories: [],
        order: 999,
        comercioId: "J7plAoTSgUmTXxaQ4gnT",
        comercioName: "La Choza del Pueblo"
    },
    {
        id: 7,
        name: "Arroz con pollo ",
        price: 3500,
        image: "https://i.postimg.cc/hGRZtyvN/arroz-cantones.jpg",
        productDetails: "",
        isVegan: false,
        isVegetarian: false,
        isGlutenFree: false,
        dietaryInfo: "",
        categories: [],
        order: 999,
        comercioId: "J7plAoTSgUmTXxaQ4gnT",
        comercioName: "La Choza del Pueblo"
    },
    {
        id: 8,
        name: "Casado con Pollo",
        price: 3500,
        image: "https://i.postimg.cc/s2qwBTTp/casado.jpg",
        productDetails: "Puedes con pollo a la plancha o empanizado ",
        isVegan: false,
        isVegetarian: false,
        isGlutenFree: false,
        dietaryInfo: "",
        categories: ["Casados"],
        order: 999,
        comercioId: "J7plAoTSgUmTXxaQ4gnT",
        comercioName: "La Choza del Pueblo"
    },
    {
        id: 9,
        name: "Sandwich Jamón y Queso ",
        price: 2000,
        image: "https://i.postimg.cc/sDDrV2q5/sandwish-jamon.webp",
        productDetails: "",
        isVegan: false,
        isVegetarian: false,
        isGlutenFree: false,
        dietaryInfo: "",
        categories: [],
        order: 999,
        comercioId: "J7plAoTSgUmTXxaQ4gnT",
        comercioName: "La Choza del Pueblo"
    },
    {
        id: 10,
        name: "Casado de Chuleta ",
        price: 3500,
        image: "https://i.postimg.cc/s2qwBTTp/casado.jpg",
        productDetails: "",
        isVegan: false,
        isVegetarian: false,
        isGlutenFree: false,
        dietaryInfo: "",
        categories: ["Casados"],
        order: 999,
        comercioId: "J7plAoTSgUmTXxaQ4gnT",
        comercioName: "La Choza del Pueblo"
    },
    {
        id: 11,
        name: "Tamal de cerdo ",
        price: 1000,
        image: "https://i.postimg.cc/VNbw3HTT/tamal.jpg",
        productDetails: "",
        isVegan: false,
        isVegetarian: false,
        isGlutenFree: false,
        dietaryInfo: "",
        categories: [],
        order: 999,
        comercioId: "J7plAoTSgUmTXxaQ4gnT",
        comercioName: "La Choza del Pueblo"
    },
    {
        id: 12,
        name: "Casado Bistec de Res",
        price: 3800,
        image: "https://i.postimg.cc/s2qwBTTp/casado.jpg",
        productDetails: "",
        isVegan: false,
        isVegetarian: false,
        isGlutenFree: false,
        dietaryInfo: "",
        categories: ["Casados"],
        order: 999,
        comercioId: "J7plAoTSgUmTXxaQ4gnT",
        comercioName: "La Choza del Pueblo"
    },
    {
        id: 13,
        name: "Ceviche y patacones",
        price: 3800,
        image: "",
        productDetails: "",
        isVegan: false,
        isVegetarian: false,
        isGlutenFree: false,
        dietaryInfo: "",
        categories: [],
        order: 999,
        comercioId: "J7plAoTSgUmTXxaQ4gnT",
        comercioName: "La Choza del Pueblo"
    },
    {
        id: 14,
        name: "Casado Carne en Salsa ",
        price: 3500,
        image: "https://i.postimg.cc/s2qwBTTp/casado.jpg",
        productDetails: "",
        isVegan: false,
        isVegetarian: false,
        isGlutenFree: false,
        dietaryInfo: "",
        categories: ["Casados"],
        order: 999,
        comercioId: "J7plAoTSgUmTXxaQ4gnT",
        comercioName: "La Choza del Pueblo"
    },
    {
        id: 15,
        name: "Chifrijo",
        price: 4500,
        image: "https://i.postimg.cc/qBLySm2j/chifrijo.jpg",
        productDetails: "",
        isVegan: false,
        isVegetarian: false,
        isGlutenFree: false,
        dietaryInfo: "",
        categories: [],
        order: 999,
        comercioId: "J7plAoTSgUmTXxaQ4gnT",
        comercioName: "La Choza del Pueblo"
    },
    {
        id: 16,
        name: "Sopa Azteca",
        price: 4000,
        image: "https://i.postimg.cc/855RpMRq/azteca.jpg",
        productDetails: "",
        isVegan: false,
        isVegetarian: false,
        isGlutenFree: false,
        dietaryInfo: "",
        categories: [],
        order: 999,
        comercioId: "J7plAoTSgUmTXxaQ4gnT",
        comercioName: "La Choza del Pueblo"
    },
    {
        id: 17,
        name: "Sopa de Mondongo ",
        price: 3500,
        image: "",
        productDetails: "",
        isVegan: false,
        isVegetarian: false,
        isGlutenFree: false,
        dietaryInfo: "",
        categories: [],
        order: 999,
        comercioId: "J7plAoTSgUmTXxaQ4gnT",
        comercioName: "La Choza del Pueblo"
    },
    {
        id: 18,
        name: "Gallo Salchichón",
        price: 1300,
        image: "https://i.postimg.cc/qBKt81v1/gallo-salchichon.webp",
        productDetails: "",
        isVegan: false,
        isVegetarian: false,
        isGlutenFree: false,
        dietaryInfo: "",
        categories: ["Gallos", "Desayunos"],
        order: 999,
        comercioId: "J7plAoTSgUmTXxaQ4gnT",
        comercioName: "La Choza del Pueblo"
    },
    {
        id: 19,
        name: "Gordon Blue",
        price: 4500,
        image: "https://i.postimg.cc/zGPkMdZ9/gordon-blue.jpg",
        productDetails: "",
        isVegan: false,
        isVegetarian: false,
        isGlutenFree: false,
        dietaryInfo: "",
        categories: [],
        order: 999,
        comercioId: "J7plAoTSgUmTXxaQ4gnT",
        comercioName: "La Choza del Pueblo"
    },
    {
        id: 20,
        name: "Arroz cantones ",
        price: 4000,
        image: "https://i.postimg.cc/hGRZtyvN/arroz-cantones.jpg",
        productDetails: "",
        isVegan: false,
        isVegetarian: false,
        isGlutenFree: false,
        dietaryInfo: "",
        categories: [],
        order: 999,
        comercioId: "J7plAoTSgUmTXxaQ4gnT",
        comercioName: "La Choza del Pueblo"
    },
    {
        id: 21,
        name: "Arroz con Cerdo",
        price: 3700,
        image: "https://i.postimg.cc/hGRZtyvN/arroz-cantones.jpg",
        productDetails: "Acompañado de papas fritas y ensalada ",
        isVegan: false,
        isVegetarian: false,
        isGlutenFree: false,
        dietaryInfo: "",
        categories: [],
        order: 999,
        comercioId: "J7plAoTSgUmTXxaQ4gnT",
        comercioName: "La Choza del Pueblo"
    },
    {
        id: 22,
        name: "Arroz con Camarones ",
        price: 4500,
        image: "https://i.postimg.cc/52LpTBgg/arroz-camarones.jpg",
        productDetails: "",
        isVegan: false,
        isVegetarian: false,
        isGlutenFree: false,
        dietaryInfo: "",
        categories: [],
        order: 999,
        comercioId: "J7plAoTSgUmTXxaQ4gnT",
        comercioName: "La Choza del Pueblo"
    },
    {
        id: 23,
        name: "Sopa Mexicana ",
        price: 3000,
        image: "",
        productDetails: "",
        isVegan: false,
        isVegetarian: false,
        isGlutenFree: false,
        dietaryInfo: "",
        categories: [],
        order: 999,
        comercioId: "J7plAoTSgUmTXxaQ4gnT",
        comercioName: "La Choza del Pueblo"
    },
    {
        id: 24,
        name: "Gallo Queso",
        price: 1200,
        image: "https://i.postimg.cc/XJHrQPyP/gallo-queso.webp",
        productDetails: "",
        isVegan: false,
        isVegetarian: false,
        isGlutenFree: false,
        dietaryInfo: "",
        categories: ["Gallos", "Desayunos"],
        order: 999,
        comercioId: "J7plAoTSgUmTXxaQ4gnT",
        comercioName: "La Choza del Pueblo"
    },
    {
        id: 25,
        name: "Filet de pescado ",
        price: 3800,
        image: "https://i.postimg.cc/mkxXnmMb/casado-pescado.jpg",
        productDetails: "",
        isVegan: false,
        isVegetarian: false,
        isGlutenFree: false,
        dietaryInfo: "",
        categories: ["Casados"],
        order: 999,
        comercioId: "J7plAoTSgUmTXxaQ4gnT",
        comercioName: "La Choza del Pueblo"
    },
    {
        id: 26,
        name: "Gallo Pinto ",
        price: 2500,
        image: "https://i.postimg.cc/9FTGQW9F/gallo-pinto.jpg",
        productDetails: "Acompañado de huevo y platano maduro.\nAdicional de Queso, tocineta, natilla, salchichón por 500 colones ",
        isVegan: false,
        isVegetarian: true,
        isGlutenFree: false,
        dietaryInfo: "",
        categories: ["Desayunos"],
        order: 999,
        comercioId: "J7plAoTSgUmTXxaQ4gnT",
        comercioName: "La Choza del Pueblo"
    },
    {
        id: 27,
        name: "Filet de pollo ",
        price: 5000,
        image: "https://i.postimg.cc/rp5bG678/filet-jalape-o.jpg",
        productDetails: "En salsa jalapeña acompañado con papas fritas y ensalada",
        isVegan: false,
        isVegetarian: false,
        isGlutenFree: false,
        dietaryInfo: "",
        categories: [],
        order: 999,
        comercioId: "J7plAoTSgUmTXxaQ4gnT",
        comercioName: "La Choza del Pueblo"
    },
    {
        id: 28,
        name: "Adcional Papas fritas ",
        price: 500,
        image: "https://i.postimg.cc/vm9RPxxw/papas-fritas.webp",
        productDetails: "",
        isVegan: false,
        isVegetarian: false,
        isGlutenFree: false,
        dietaryInfo: "",
        categories: [],
        order: 999,
        comercioId: "J7plAoTSgUmTXxaQ4gnT",
        comercioName: "La Choza del Pueblo"
    },
    {
        id: 29,
        name: "Ceviche y Tostadas",
        price: 3500,
        image: "",
        productDetails: "",
        isVegan: false,
        isVegetarian: false,
        isGlutenFree: false,
        dietaryInfo: "",
        categories: [],
        order: 999,
        comercioId: "J7plAoTSgUmTXxaQ4gnT",
        comercioName: "La Choza del Pueblo"
    },
    {
        id: 30,
        name: "Adicional Carne en Salsa ",
        price: 700,
        image: "https://i.postimg.cc/Rh1V2b39/carne-en-salsa.jpg",
        productDetails: "",
        isVegan: false,
        isVegetarian: false,
        isGlutenFree: false,
        dietaryInfo: "",
        categories: ["Adicionales", "Desayunos"],
        order: 999,
        comercioId: "J7plAoTSgUmTXxaQ4gnT",
        comercioName: "La Choza del Pueblo"
    },
    {
        id: 31,
        name: "Gallo Picadillo",
        price: 2000,
        image: "https://i.postimg.cc/Nf4j4Sqk/gallo-picadillo.jpg",
        productDetails: "",
        isVegan: false,
        isVegetarian: false,
        isGlutenFree: false,
        dietaryInfo: "",
        categories: ["Gallos", "Desayunos"],
        order: 999,
        comercioId: "J7plAoTSgUmTXxaQ4gnT",
        comercioName: "La Choza del Pueblo"
    },
    {
        id: 32,
        name: "Sopa Ranchera",
        price: 3000,
        image: "",
        productDetails: "",
        isVegan: false,
        isVegetarian: false,
        isGlutenFree: false,
        dietaryInfo: "",
        categories: [],
        order: 999,
        comercioId: "J7plAoTSgUmTXxaQ4gnT",
        comercioName: "La Choza del Pueblo"
    },
    {
        id: 33,
        name: "Filet de pollo a la plancha",
        price: 4000,
        image: "https://i.postimg.cc/4yJtntR6/filet-pollo.jpg",
        productDetails: "Acompañado de papas fritas y ensalada",
        isVegan: false,
        isVegetarian: false,
        isGlutenFree: false,
        dietaryInfo: "",
        categories: [],
        order: 999,
        comercioId: "J7plAoTSgUmTXxaQ4gnT",
        comercioName: "La Choza del Pueblo"
    },
    {
        id: 34,
        name: "Sopa de Mariscos ",
        price: 4500,
        image: "https://i.postimg.cc/9XRHNS3j/sopa-mariscos.jpg",
        productDetails: "",
        isVegan: false,
        isVegetarian: false,
        isGlutenFree: false,
        dietaryInfo: "",
        categories: [],
        order: 999,
        comercioId: "J7plAoTSgUmTXxaQ4gnT",
        comercioName: "La Choza del Pueblo"
    }
];
